apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7tkz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0061-tenant/tkrw-pr712-0075-0061-app/devfile-sample-7tkz@sha256:d3dd5ac000f63b75291014cbc7a5770eada9f9c56e4feacd44ea1f04d5242803
        name: my-nodejs
        resources: {}
status: {}
